---
title: "Bibliography"
author: "Stephane Berhault"
date: "2023-08-09"
format: html
---

# Bibliography

Airly. (n.d.). *How does humidity affect air quality? All you need to know*. [airly.org/en/how-does-humidity-affect-air-quality-all-you-need-to-know/](https://airly.org/en/how-does-humidity-affect-air-quality-all-you-need-to-know/)

AirNow. (n.d.). *Using air quality index*. [www.airnow.gov/aqi/aqi-basics/using-air-quality-index](https://www.airnow.gov/aqi/aqi-basics/using-air-quality-index)

American Lung Association. (n.d.). *Key findings: State of the air*. [www.lung.org/research/sota/key-findings](https://www.lung.org/research/sota/key-findings)

California Air Resources Board. (n.d.). *Carbon monoxide & health*. [ww2.arb.ca.gov/resources/carbon-monoxide-and-health](https://ww2.arb.ca.gov/resources/carbon-monoxide-and-health)

Centers for Disease Control and Prevention, Agency for Toxic Substances and Disease Registry. (2014, October 21). *Medical management guidelines for sulfur dioxide*. [wwwn.cdc.gov/TSP/MMG/MMGDetails.aspx?mmgid=249&toxid=46](https://wwwn.cdc.gov/TSP/MMG/MMGDetails.aspx?mmgid=249&toxid=46)

Centers for Disease Control and Prevention, Agency for Toxic Substances and Disease Registry. (2023, April 12). *Toxic substances portal - Nitrogen oxides*. [wwwn.cdc.gov/TSP/ToxFAQs/ToxFAQsDetails.aspx?faqid=396&toxid=69](https://wwwn.cdc.gov/TSP/ToxFAQs/ToxFAQsDetails.aspx?faqid=396&toxid=69)

Congressional Budget Office. (2023, May). *Reducing emissions from transportation*. [www.cbo.gov/publication/60030](https://www.cbo.gov/publication/60030)

Environmental Protection Agency. (n.d.-a). *Evolution of the Clean Air Act*. [www.epa.gov/clean-air-act-overview/evolution-clean-air-act](https://www.epa.gov/clean-air-act-overview/evolution-clean-air-act)

Environmental Protection Agency. (n.d.-b). *Health effects of ozone pollution*. [www.epa.gov/ground-level-ozone-pollution/health-effects-ozone-pollution](https://www.epa.gov/ground-level-ozone-pollution/health-effects-ozone-pollution)

Environmental Protection Agency. (n.d.-c). *Particulate matter (PM) basics*. [www.epa.gov/pm-pollution/particulate-matter-pm-basics](https://www.epa.gov/pm-pollution/particulate-matter-pm-basics)

Federal Transit Administration. (n.d.). *NTD data tables*. American Public Transportation Association. [www.apta.com/research-technical-resources/transit-statistics/ntd-data-tables/](https://www.apta.com/research-technical-resources/transit-statistics/ntd-data-tables/)

Fuller, R., Landrigan, P. J., Balakrishnan, K., Bathan, G., Bose-O'Reilly, S., Brauer, M., Caravanos, J., Chiles, T., Cohen, A., Corra, L., Cropper, M., Ferraro, G., Hanna, J., Hanrahan, D., Hu, H., Hunter, D., Janata, G., Kupka, R., Lanphear, B., . . . Yadama, G. N. (2022). Pollution and health: A progress update. *The Lancet Planetary Health*, *6*(6), e535-e547. [www.thelancet.com/journals/lanplh/article/PIIS2542-5196(22)00090-0/fulltext](https://www.thelancet.com/journals/lanplh/article/PIIS2542-5196(22)00090-0/fulltext)

Jacobs, E. T., Burgess, J. L., & Abbott, M. B. (2018). The Donora smog revisited: 70 years after the event that inspired the clean air act. *American Journal of Public Health*, *108*(S2), S85-S88. [www.ncbi.nlm.nih.gov/pmc/articles/PMC5922205/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5922205/)

Manisalidis, I., Stavropoulou, E., Stavropoulos, A., & Bezirtzoglou, E. (2020). Environmental and health impacts of air pollution: A review. *Frontiers in Public Health*, *8*, 14. [www.ncbi.nlm.nih.gov/pmc/articles/PMC7044178/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7044178/)

National Oceanic and Atmospheric Administration. (n.d.). *What are a nautical mile and a knot?* [oceanservice.noaa.gov/facts/nautical-mile-knot.html](https://oceanservice.noaa.gov/facts/nautical-mile-knot.html)

National Weather Service. (n.d.). *Pressure and winds*. [www.weather.gov/source/zhu/ZHU_Training_Page/winds/pressure_winds/Pressure.htm](https://www.weather.gov/source/zhu/ZHU_Training_Page/winds/pressure_winds/Pressure.htm)

Oregon Wildfire Response and Recovery. (n.d.). *Wildfire prevention*. [wildfire.oregon.gov/prevention](https://wildfire.oregon.gov/prevention)

World Health Organization. (2014, March 25). *7 million premature deaths annually linked to air pollution*. [www.who.int/news/item/25-03-2014-7-million-premature-deaths-annually-linked-to-air-pollution](https://www.who.int/news/item/25-03-2014-7-million-premature-deaths-annually-linked-to-air-pollution)

World Health Organization. (2022, October 31). *Lead poisoning and health*. [www.who.int/news-room/fact-sheets/detail/lead-poisoning-and-health](https://www.who.int/news-room/fact-sheets/detail/lead-poisoning-and-health)

Zhang, Y., Cooper, O. R., Gaudel, A., Thompson, A. M., Nédélec, P., Ogino, S. Y., & West, J. J. (2018). Tropospheric ozone change from 1980 to 2010 dominated by equatorward redistribution of emissions. *Nature Geoscience*, *11*, 637-644. [acp.copernicus.org/articles/18/15003/2018/](https://acp.copernicus.org/articles/18/15003/2018/)
